### ISSUE TITLE
老哥，爬取链接格式应该是什么样的

### ISSUE THREAD

**Issue by Coincedence47** [VoidmatrixHeathcliff/EroCoolSpider#1]
/detail/1866160o351080.html
https://zha.erocool.me/detail/1866160o351080.html
类似这两种全部都是获取原始信息失败。没学过Python，看了代码不知道哪有问题，是我操作方式不太对吗

**Comment by VoidmatrixHeathcliff** [comment]
你好，是第二种传参方式，即使用完整的链接：https://zha.erocool.me/detail/1866160o351080.html
获取网页原始信息失败可能是网络问题，刚刚测试过了这个链接可以爬取

**Comment by Coincedence47** [comment]
感谢！还行问下是必须有开代理才能爬取吗，我开了代理不跳信息也不下载Q~Q，是需要单独设置防火墙规则吗

**Comment by VoidmatrixHeathcliff** [comment]
目前我这边的网络环境无论是否科学上网都可以进行爬取（或进入网站），结合之前其他使用者的反馈，基本可以确定是网络环境的问题，具体的防火墙规则或者ip过滤规则目前还没有测试，不过你或许可以试一下手机热点？😋

**Comment by Coincedence47** [comment]
OK，OK，十分感谢您的帮助！

**Comment by VoidmatrixHeathcliff** [comment]
如果可以的话，请在爬取成功后通过issue或邮件反馈给我具体的情况，不胜感激

**Comment by Coincedence47** [comment]
换了手机热点依然不行，应该是我电脑哪个地方设置被我搞坏了。

**Comment by VoidmatrixHeathcliff** [comment]
😰浏览器可以打开这个网页吗？

**Comment by Coincedence47** [comment]
浏览器不需要挂代理可以直接访问

**Comment by Coincedence47** [comment]
这是我觉得最诡异的地方。

**Comment by VoidmatrixHeathcliff** [comment]
可能是网站对于您所在地区的headers有限制要求，可以打开浏览器复制网页请求的headers替换掉`main.py`中的headers，如果不清楚如何操作，可以将网页的headers发送给我，稍后为为您提供一份新的代码作为测试使用

**Comment by Coincedence47** [comment]
好的，十分感谢！我先尝试解决一下，实在不行就得麻烦您了！

**Comment by Coincedence47** [comment]
我改了main里面的useragent 依然没有用😂
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**Comment by VoidmatrixHeathcliff** [comment]
这种情况在代码调试完毕后没有出现过，之前有过一次是因为大规模请求被网站暂时封禁了ip，有没有可能换一台设备进行测试？对于这种问题我也很困惑😢

**Comment by Coincedence47** [comment]
辛苦您了，我换台设备再试试吧！十分感谢您的解答

**Comment by VoidmatrixHeathcliff** [comment]
没关系的，后续这个问题仍未解决欢迎邮件通知我，我会发您我的其他联系方式，咱们细谈

**Comment by Coincedence47** [comment]
好的，谢谢老哥！👍
