### ISSUE TITLE
关于网站地址变化的问题

### ISSUE THREAD

**Issue by Zyyans** [VoidmatrixHeathcliff/EroCoolSpider#2]
咱觉得你可以从他们的地址发布页 https://tellmeurl.com/erocool/ 获取地址

**Comment by VoidmatrixHeathcliff** [comment]
如果我没记错的话，这个地址发布页的地址也变更过

**Comment by Zyyans** [comment]
从咱使用这个网站开始，至今应该是没有发布页的变动的
而且，从咱在其他网站的经验来看，即使本体提示的发布页变动，原来的发布页也不会删除
只能说，应该是比使用当前地址更优的解法(｀･ω･)
------------------ 原始邮件 ------------------
发件人: Voidmatrix ***@***.***&gt;
发送时间: 2021年3月19日 18:02
收件人: VoidmatrixHeathcliff/EroCoolSpider ***@***.***&gt;
抄送: 蠢驴 ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[VoidmatrixHeathcliff/EroCoolSpider] 关于网站地址变化的问题 (#2)





 
如果我没记错的话，这个地址发布页的地址也变更过

**Comment by VoidmatrixHeathcliff** [comment]
新年前后发布页换过一次，如果不是换过也是临时关停过一段时间；不过确实是比手动更新地址要舒服得多，不如你来修改一下readme，然后push给我~😉
